### ISSUE TITLE
Prototype Pollution in JSON5 via Parse Method

### ISSUE THREAD

**Issue by pedroresende** [tleunen/eslint-import-resolver-babel-module#121]
Please update babel-plugin-module-resolver to version 5.0.0 in order to address the [Prototype Pollution in JSON5 via Parse Method](https://github.com/advisories/GHSA-9c47-m6qq-7p4h)

**Comment by nchevsky** [comment]
@tleunen Could we please get a new release that depends on the latest [`babel-plugin-module-resolver v5.0.0`](https://github.com/tleunen/babel-plugin-module-resolver/blob/master/CHANGELOG.md#500-2023-01-09)? 🙏🏻 This is the last dependency we need updated to finally stop all reliance on vulnerable versions of JSON5.

**Comment by tleunen** [comment]
Released :) Thanks!

**Comment by dlong500** [comment]
@tleunen Is this dependency update going to make this module incompatible with versions of nodejs earlier than 16.x? Version 5.0.0 of `babel-plugin-module-resolver` has a breaking change dropping support for earlier versions of nodejs.

**Comment by tleunen** [comment]
For this plugin, nope because we still build it with node10 in the babel config, but the babel plugin is not guaranteed to work properly as it has node 16 in its config.
The breaking change is mostly that the minimum tested/built version is now 16.x
