### ISSUE TITLE
How to configure custom root?

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [tleunen/eslint-import-resolver-babel-module#26]
My webpack configures a custom root at ```./src```
So my .babelrc looks like this:
```json
{
  "presets": [
    "es2015",
    "stage-0",
    "react"
  ],
  "plugins": [
    ["module-resolver", {
      "root": ["./src"],
      "alias": {
        "@collections": "lib/collections"
      }
    }]
  ]
}
```
And the app builds just fine
However, I can still see linting problems on my editor (Atom)
My .eslintrc looks like this
```json
  "settings": {
    "import/resolver": {
      "babel-module": {}
    }
  },
```
Should this work as it is or should I configure the root folder somewhere?

**Comment by tleunen** [comment]
Indeed, this should work. No need to configure anything in the `babel-module` option for the import resolver, unless you're using a file extension other than `.js`.

I don't see any error in your config though. Except that you're mentioning webpack. The webpack custom resolver is not required if you're using the `babel-plugin-module-resolver`.

**Comment by rafaelcorreiapoli** [comment]
I mentioned webpack because it is settings a custom root folder for my project.
I noticed that when I run eslint from bash, I get this error:
```
error  Resolve error: unable to load resolver "babel-module"
```
But I followed all the instructions:
Installing and configuring these:
https://github.com/tleunen/babel-plugin-module-resolver
https://github.com/benmosher/eslint-plugin-import
https://github.com/tleunen/eslint-import-resolver-babel-module

**Comment by tleunen** [comment]
Would you have an test repo with the issue? It would help me to find the error and better help you.

If you're using `babel-plugin-module-resolver`, the custom root with webpack is not required though.
Are you sure you properly installed all the packages? Because your error seems to report the `eslint-import-resolver-babel-module` package is not installed.

**Comment by satya164** [comment]
I'm facing the same issue. The package is installed correctly. example https://github.com/satya164/react-navigation-addons

lemme know what details you need.
