### ISSUE TITLE
Breakage as of v2.1: "unable to load resolver"

### ISSUE THREAD

**Issue by rkirsling** [tleunen/eslint-import-resolver-babel-module#29]
`eslint-import-resolver-babel-module@2.1.0` appears to be broken.

Using the trivial repo example below, executing `eslint "src/**"` produces the error:
```bash
1:1   error  Resolve error: unable to load resolver "babel-module"
```

Downgrading to v2.0.1 fixes the issue.

(_Note: This is tied to `babel-plugin-module-resolver@2.3.0`, but Babel is resolving correctly._)

-----

**package.json**
```json
{
  "name": "test",
  "version": "0.0.0",
  "devDependencies": {
    "babel-plugin-module-resolver": "2.3.0",
    "babel-preset-es2015": "6.18.0",
    "eslint": "3.9.1",
    "eslint-import-resolver-babel-module": "2.1.0",
    "eslint-plugin-import": "2.1.0"
  }
}
```

**.babelrc**
```json
{
    "presets": ["es2015"],
    "plugins": [
        ["module-resolver", { "alias": { "x": "./src" } }]
    ]
}
```

**.eslintrc.js**
```js
module.exports = {
    parserOptions: {
      ecmaVersion: 6,
      sourceType: 'module'
    },
    plugins: [
      'import'
    ],
    settings: {
      'import/resolver': { 'babel-module': {} },
    },
    rules: {
      'import/no-unresolved': 'error'
    }
};
```

**src/foo/foo.js**
```js
import bar from 'x/bar/bar';

const foo = bar(10);

export default foo;
```

**src/bar/bar.js**
```js
function bar(x) {
  return x * 2;
}

export default bar;
```

**Comment by tleunen** [comment]
I believe the `eslint` you're using in your command is a global eslint, which cannot find the plugin.
I've tested the example you provide, while using the local eslint, and I don't have any errors.
Here's what I added in the package.json:
```
"scripts": {
    "lint": "eslint 'src/**'"
  }
```

**Comment by rkirsling** [comment]
It's local—I actually ran `node_modules/.bin/eslint "src/**"` but didn't feel like writing all that. :smile:

**Comment by tleunen** [comment]
So this is actually the error I fixed a couple of minutes ago, in this commit https://github.com/tleunen/eslint-import-resolver-babel-module/commit/a925e3fb87128260f67d1f09ae49c426f5daf80a

I thought I had released a new version but I didn't. It's now done and 2.1.1 is available ;)

**Comment by rkirsling** [comment]
Confirmed—thanks!
