### ISSUE TITLE
The eslint plugin can catch unrelated errors

### ISSUE THREAD

**Issue by tleunen** [tleunen/eslint-import-resolver-babel-module#41]
When an error is inside the babelrc file, this eslint plugin can catch these errors, but they are unrelated to eslint or the babel module resolver plugin.

Example:
```
[eslint-import-resolver-babel-module] ReferenceError: Unknown plugin "transform-object-rest-spread" specified in ...
```

**Comment by blackxored** [comment]
I'm having this same issue apparently. Why was it closed?
