### ISSUE TITLE
can not resolve some module in sublime text

### ISSUE THREAD

**Issue by craigcosmo** [tleunen/eslint-import-resolver-babel-module#42]
<img width="846" alt="screen shot 2017-02-15 at 11 29 42 pm" src="https://cloud.githubusercontent.com/assets/538657/22984210/3a58961e-f3d7-11e6-9de0-74a9f0f023fa.png">

I had `sublime linter` & `sublime contrib eslint` installed.

**babel config**
```json
[
	"module-resolver",
	{
		"root": [
			"app/**"
		]
	}
]
```

**eslint config**
```json
"settings":{
		"import/resolver": {
			"babel-module": {}
		}
	},
"plugins": [
		"react",
		"json",
		"import"
	],
"rules": {
		"import/no-unresolved": "error"
	}
```
Good thing: sublime can recognize the module from node_modules.

Bad thing: sublime can not recognize the modules  `config.js` and `header.js`

If I disable babel resolver, sublime will not even recognize module from node_modules.

I'm not sure where the problem comes from, sublime or sublime eslint package or this.

**Comment by craigcosmo** [comment]
any clue where the bug come from?

**Comment by tleunen** [comment]
What version of this plugin are you using? Using v3.0.0 should be better in your case as a fix for the globbing was added.

If you're already using the latest version, could you try to reproduce the issue in a small project so I can take a deeper look?

**Comment by craigcosmo** [comment]
Yeah, I'm using version 3.0.0.

here's the demo https://github.com/craigcosmo/simple-webpack

to reproduce:
install sublime
install sublime eslint package
install sublime eslint contrib
open the project in sublime - of course install node_modules before opening it sublime
then open file home.js
you see some like the screenshot below

<img width="474" alt="screen shot 2017-02-27 at 10 31 43 pm" src="https://cloud.githubusercontent.com/assets/538657/23367361/9259619a-fd3c-11e6-830e-b3264d92b8e4.png">

the red dot indicate that file is not resolved.

**Comment by tleunen** [comment]
Thanks @craigcosmo! I have targeted the error. Sublime and Atom handle differently when things run inside a file.

For example, atom keeps its working directory with the project root while Sublime has its working directory set to the directory of the open file.

This will require an update in both babel-plugin-module-resolver and this eslint plugin. I'll see if I can do it tonight, otherwise it will be tomorrow. Thanks for your patience.

**Comment by craigcosmo** [comment]
just download the latest version of `eslint-import-resolver-babel-module` and `babel-plugin-module-resolver`. I still see the error

**Comment by tleunen** [comment]
With both beta versions? Hmm.. Is it reproducible again in your test repo above?

**Comment by craigcosmo** [comment]
With beta versions of both package, this issue is resolved.
