### ISSUE TITLE
module resolving when cwd === "babelrc"

### ISSUE THREAD

**Issue by mikemonteith** [tleunen/eslint-import-resolver-babel-module#43]
babel-plugin-module-resolver treats the string "babelrc" as a special case, which is not supported by this resolver.
From babel-plugin Readme:
> cwd: By default, the working directory is the one used for the resolver, but you can override it for your project.
The custom value babelrc will make the plugin look for the closest babelrc configuration based on the file to parse.

babel-plugin relevant code:
https://github.com/tleunen/babel-plugin-module-resolver/blob/master/src/index.js#L53

**Comment by brannon** [comment]
I just ran into this as well.  Debugging through this plugin, I can see that it's not translating the value `babelrc` to the directory of the `.babelrc` file, it's using it as a literal directory name.

**Comment by tleunen** [comment]
Thank you for reporting this @mikemonteith. I'll try to take a look at it this weekend if nobody takes it before.

**Comment by laurence-hudson-tessella** [comment]
Have submitted a trival PR. It resolve this issue for me (babelrc & eslintrc are both in the repo root directory, but I still need to set `cwd: 'babelrc'` because I need to run `babel-node` from directories which aren't the repo root). I'm not sure about other contexts.

**Comment by brannon** [comment]
Any luck with the pull request?

**Comment by laurence-hudson-tessella** [comment]
Nope, it has been open for >20 days, without comment. #45.  In the short term I've just been using `"eslint-import-resolver-babel-module": "laurence-hudson-tessella/eslint-import-resolver-babel-module#8c76c7d11285f8297a53462fed77c4cc5d5c8e03",` in my devDeps.

**Comment by tleunen** [comment]
I'm sorry, I'm very busy since the beginning of the year.

We need to update the plugin to handle the `babelrc` string. Pretty much the same logic as what we can find here https://github.com/tleunen/babel-plugin-module-resolver/blob/master/src/index.js#L78-L87. I might also export the function from the babel plugin to keep the logic in one place only.

**Comment by tleunen** [comment]
nvm, it still breaks inside atom or sublime. Will continue to investigate

**Comment by tleunen** [comment]
Please try again with 4.0.0-beta.1 :)

**Comment by laurence-hudson-tessella** [comment]
Thanks Tommy, `4.0.0-beta.1` with `3.0.0-beta.0` of the babel plugin works in my scenario (ie babelrc & eslintrc are both in the repo root directory).

**Comment by tleunen** [comment]
Great! Thank you for reporting this.
