### ISSUE TITLE
Imports w/ query

### ISSUE THREAD

**Issue by alexfedoseev** [tleunen/eslint-import-resolver-babel-module#59]
Is there any way to handle imports w/ query (used by webpack loader)?

```
import coverImage from './images/cover.jpg?preset=cover';
```

**Comment by tleunen** [comment]
Hi @alexfedoseev, do you know if it's only an eslint error to now handle these paths, or it's not handled at all by the babel plugin (https://github.com/tleunen/babel-plugin-module-resolver)?

**Comment by alexfedoseev** [comment]
Hi @tleunen, this is only eslint issue, it works great w/ babel plugin.

Here is the repo to reproduce: https://github.com/alexfedoseev/blog

**Comment by tleunen** [comment]
Thanks for confirming.

I'm guessing it's not possible to use both the webpack resolver and this one. Since they will both fail probably.

I agree that we should probably support it here too. It shouldn't take long, the logic should be fairly easy to implement. I'll take a look tomorrow at the latest.

**Comment by alexfedoseev** [comment]
Thanks a lot, @tleunen!

**Comment by tleunen** [comment]
@alexfedoseev I released a `4.0.0-beta.2`, but this version is only compatible with babel-plugin-module-resolver 3.0 beta. So you should install `3.0.0-beta.3` for the babel plugin too.

**Comment by alexfedoseev** [comment]
@tleunen Thanks for the quick fix! I just tested it, initial error is gone, but now it throws another one:

```
11:24  error  Missing file extension "jpg" for "./images/cover.jpg?preset=cover"  import/extensions
```

If I remove query, then this error is gone.

**Comment by tleunen** [comment]
You need to add the image extension (.jpg for example) in the ignore list for the `import/extensions` settings. See https://github.com/benmosher/eslint-plugin-import#importignore

**Comment by alexfedoseev** [comment]
Just tried and it doesn't work: still reports `Missing file extension` w/ query and passes w/o query (either w/ or w/o extension in `ignore` list).

**Comment by tleunen** [comment]
Could you create a PR on your repo with what you tested? I'd like to play with it.

**Comment by alexfedoseev** [comment]
@tleunen Sure! Here it is: https://github.com/alexfedoseev/blog/pull/1
