### ISSUE TITLE
Error matching subfolders inside the alias

### ISSUE THREAD

**Issue by GabrielDuarteM** [tleunen/eslint-import-resolver-babel-module#65]
When i have an alias to a folder that has a subfolder inside, `babel-plugin-module-resolver` is able to identify with no problems when i try to import something from the subfolder, but when i have the rule `import/no-extraneous-dependencies` enabled, eslint throws me an error stating that i should install `@common/utils`, not recognizing that i have a `utils` folder inside the `@common` alias.

Is this a known bug?

**Comment by tayfunyasar** [comment]
I'm having same error.

Here is my configs.

package.json

```
{
  "name": "MyProject",
  "dependencies": {
  ..
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-eslint": "^7.2.3",
    "babel-jest": "20.0.3",
    "babel-plugin-module-resolver": "^2.7.1",
    "babel-preset-react-native": "^2.0.0",
    "eslint": "^4.6.1",
    "eslint-config-airbnb": "^15.1.0",
    "eslint-import-resolver-babel-module": "2.2.1",
    "eslint-plugin-babel": "^4.1.2",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "eslint-plugin-prefer-object-spread": "^1.2.1",
    "eslint-plugin-react": "^7.2.1",
    "eslint-plugin-react-native": "^3.1.0",
  }
}

```
.babelrc
```
{
  "presets": ["react-native"],
  "plugins": [
    ["module-resolver", {
      "root": ["./app"],
      "alias": {
        "~": "/",
        "@components": "/components",

        "underscore": "lodash"
      }
    }]
  ]
}

```
.eslintrc
```
{
  "parser": "babel-eslint",
  "extends": [
    "airbnb"
  ],
  "plugins": [
    "react",
    "babel",
    "prefer-object-spread",
    "import"
  ],
  "settings": {
    "import/resolver": {
        "babel-module": {}
      }
  },
  "rules": {
    ...
  }
}

```

usage:
`import MessageBox from '@components/ui/MessageBox';
`
errors:
@components/ui' sh```
ould be listed in the project's dependencies. Run 'npm i -S @components/ui' to add it (import/no-extraneous-dependencies) 
Absolute imports should come before relative imports. (import/first) 
Unable to resolve path to module '@components/ui/MessageBox'. (import/no-unresolved) 
Missing file extension for "@components/ui/MessageBox" (import/extensions)
```

**Comment by tleunen** [comment]
The problem is probably the way you setup the alias. `"@components": "/components",` shouldn't have a leading `/`, otherwise it will look in the wrong directory (the system root).

Removing the slash should make it work.
