### ISSUE TITLE
Unable to make 4.0.0-beta.5 work

### ISSUE THREAD

**Issue by Justkant** [tleunen/eslint-import-resolver-babel-module#72]
I think that the `4.0.0-beta.5` is not working but the `3.0.0` is working with the same config.

---

<details><summary><code>.babelrc</code></summary><p>

```json
{
  "presets": ["react-native"],
  "plugins": [
    [
      "module-resolver",
      {
        "root": ["./src"],
        "extensions": [
          ".js",
          ".ios.js",
          ".android.js"
        ]
      }
    ]
  ]
}

```
</p></details>

---

<details><summary><code>.eslintrc.js</code></summary><p>

```javascript
exports.root = true;

exports.plugins = ['prettier'];

exports.extends = [
  'airbnb',
  'prettier',
  'prettier/react',
  'plugin:react-native/all',
];

exports.parser = 'babel-eslint';

exports.env = {
  node: true,
  jest: true,
};

exports.settings = {
  'import/resolver': {
    'babel-module': {
      root: ['./src'],
      extensions: ['.js', '.ios.js', '.android.js'],
    },
  },
  react: {
    version: '16.0',
  },
};

exports.globals = {};

exports.rules = {
  'prettier/prettier': ['error', { trailingComma: 'all', singleQuote: true }],
  // `.jsx` extension cannot be used with React Native
  // https://github.com/airbnb/javascript/issues/982
  'react/jsx-filename-extension': ['error', { extensions: ['.js', '.jsx'] }],
};
```
</p></details>

**Comment by Justkant** [comment]
I got the `4.0.0-beta.5` working with the same config after updating `babel-plugin-module-resolver` from `2.7.1` to `3.0.0-beta.5`

I think the issue here is the difference with the latest of `babel-plugin-module-resolver` vs `eslint-import-resolver-babel-module` while installing those packages actually

```bash
$ y info eslint-import-resolver-babel-module dist-tags
yarn info v1.2.1
{ latest: '4.0.0-beta.3',
  beta: '4.0.0-beta.5' }
✨  Done in 0.14s.
$ y info babel-plugin-module-resolver dist-tags
yarn info v1.2.1
{ latest: '2.7.1',
  beta: '3.0.0-beta.5' }
✨  Done in 0.15s.
```

**Comment by tleunen** [comment]
Argh. I made a mistake when publishing the beta.4, so I removed it and did a new beta.5 with the right tag. I would have thought the latest would go back to v3, not the latest published version :s 

This is my fault. Sorry. I'll really try to push the final versions in the next few days to resolve this issue.
In the meantime, you should use the eslint plugin v3 with the babel plugin v2. Otherwise, use the beta versions.

**Comment by Justkant** [comment]
No problem, I just wanted to ping back when I saw the beta for `babel-plugin-module-resolver`.

BTW I use the beta now and saw no problem 👍
