### ISSUE TITLE
npm update

### ISSUE THREAD

**Issue by andrevenancio** [tleunen/eslint-import-resolver-babel-module#73]
Not sure I'm missing something but when I run `npm i --save eslint-import-resolver-babel-module` I get the version 4.0.0-beta.3

This version requires me to install peerDependency as per the warning
```bash
npm WARN eslint-import-resolver-babel-module@4.0.0-beta.3 requires a peer of babel-plugin-module-resolver@>3.0.0-beta but none is installed. You must install peer dependencies yourself.
```

However running `npm i --save babel-plugin-module-resolver@3.0.0-beta` return an error

```bash
npm ERR! code ETARGET
npm ERR! notarget No matching version found for babel-plugin-module-resolver@3.0.0-beta
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

Am I missing something?

**Comment by reohjs** [comment]
I think it's a semver issue - the peerDependency should be `^3.0.0-beta.0`

Though, even after installing `beta.0`, I'm getting `has incorrect peer dependency babel-core@^6.0.0` cause I have `^7.0.0-beta.2` but the constraint is set to `^6.0.0 || >7.0.0-alpha`...

**Comment by ctavan** [comment]
@tleunen the incorrect tag is causing some trouble for modules using automated dependency updating mechanisms. Would you mind correcting the `latest` label or is the v3 coming in the next days anyways?

**Comment by tleunen** [comment]
Yes, we need to fix #74 first, I'll investigate again tonight.
We released officially the babel plugin, so an official release of the eslint plugin will come soon, once we fix the issue as I said. I didn't plan that one :( Ideally, both would have been updated at the same time

**Comment by rkirsling** [comment]
Any further word on this?

**Comment by rkirsling** [comment]
This shouldn't be closed until v4 is released...?
"You can't simply use this package without locking its version" is an outstanding issue which seems to only be tracked here.

**Comment by tleunen** [comment]
Agreed. I plan to release v4 with a support for Babel 6 only, and a v5 beta for Babel 7.
More info tomorrow.

**Comment by tleunen** [comment]
v4 has been released with babel 6 only.
v5.beta with babel 7 will be published very soon.
