### ISSUE TITLE
resolver messes up with @babel/core 

### ISSUE THREAD

**Issue by Nopzen** [tleunen/eslint-import-resolver-babel-module#87]
Hello 👋 

Im running in to this super wired issue where i set

**.eslintrc**
```json
"settings": {
      "import/resolver": {
        "babel-module": {}
      }
    }
```

**.babelrc**
```json
{
  "presets": [
    ["@babel/env", {
      "targets": {
        "node": "8.9"
      }
    }],
    "@babel/flow"
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    ["module-resolver", {
      "root": ["./src"],
      "alias": {
        "@middlewares": "./src/middlewares",
        "@controllers": "./src/controllers",
        "@models": "./src/models"
      }
    }]
  ]
}
```

i get following error: `Resolve error: Cannot find module 'babel-core` see attatched
![skaermbillede 2018-06-14 kl 21 27 53](https://user-images.githubusercontent.com/2326591/41433723-0e687bbc-701a-11e8-9b57-be053a215375.png)

I can see that this project is has a peerDepencency on babel-core @v6 so this kinda eliminates me for using it with my @babel/core v7?

**Comment by Nopzen** [comment]
never mind, i spend 2 hrs googling the wrong things and just found your v5-beta closing

**Comment by lsps9150414** [comment]
@Nopzen Could you share more on what you found? I'm getting the same errors.
