### ISSUE TITLE
Any chance we can get v5 as a latest release?

### ISSUE THREAD

**Issue by dlong500** [tleunen/eslint-import-resolver-babel-module#97]
There hasn't been an update to the beta series of v5 since last August.  That version has been working for me, but I'm wondering why it hasn't made it out of beta for so long.  Is there something holding it back or is it unstable in some way?

**Comment by tunnckoCore** [comment]
Seems to fix the 

```
Test Suites: 1 skipped, 11 passed, 11 of 18 total
Tests:       1 skipped, 11 passed, 12 total
Snapshots:   0 total
Time:        7s[eslint-import-resolver-babel-module] TypeError: Cannot read property 'find' of undefined
    at result.plugins.filter.plugin (/home/charlike/develop/mono/node_modules/eslint-import-resolver-babel-module/lib/index.js:20:50)
    at Array.filter (<anonymous>)
    at getPlugins (/home/charlike/develop/mono/node_modules/eslint-import-resolver-babel-module/lib/index.js:19:27)

```

issue for me. So it looks like it worth releasing it as `latest`.

**Comment by tleunen** [comment]
Yes, I'll make a release tonight. Thanks for the reminder @dlong500 and @tunnckoCore

**Comment by tleunen** [comment]
v5 released. Thank you.
